name = "Xoodyak_R3"
[language]
vhdl.version = "2008"

[rtl]
sources = [
    "src_rtl/design_pkg.vhd",
    "src_rtl/xoodoo_globals.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/xoodoo_rc.vhd",
    "src_rtl/xoodoo_round.vhd",
    "src_rtl/xoodoo_register.vhd",
    "src_rtl/xoodoo_n_rounds.vhd",
    "src_rtl/xoodoo.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/LWC.vhd",
]
top = "LWC"

[tb]
sources = [
    # "src_tb/LWC_TB_compatibility_pkg.vhd",
    # "src_tb/LWC_pkg_tb.vhd",
    "src_tb/LWC_TB.vhd"
]
top = "LWC_TB"
[tb.parameters]
G_FNAME_PDI = {file="KAT/v1/pdi.txt"}
G_FNAME_SDI = {file="KAT/v1/sdi.txt"}
G_FNAME_DO  = {file="KAT/v1/do.txt"}